// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       string `json:"id"`
	UserName string `json:"user_name"`
	Text     string `json:"text"`
}

type CreateComment struct {
	ID       string `json:"id"`
	UserName string `json:"user_name"`
	Text     string `json:"text"`
}

type CreatePost struct {
	ID       string `json:"id"`
	UserName string `json:"user_name"`
	Title    string `json:"title"`
	Text     string `json:"text"`
}

type GetPost struct {
	Post *Post `json:"post"`
}

type Mutation struct {
}

type Post struct {
	ID       string     `json:"id"`
	UserName string     `json:"user_name"`
	Title    string     `json:"title"`
	Text     string     `json:"text"`
	Comments []*Comment `json:"comments"`
}

type Posts struct {
	Posts []*Post `json:"posts"`
}

type Query struct {
}
