// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID              string     `json:"id"`
	PostID          string     `json:"postId"`
	Content         string     `json:"content"`
	AuthorID        string     `json:"authorId"`
	ParentCommentID *string    `json:"parentCommentId,omitempty"`
	ChildComments   []*Comment `json:"childComments"`
}

type Mutation struct {
}

type Post struct {
	ID              string     `json:"id"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	AuthorID        string     `json:"authorId"`
	Comments        []*Comment `json:"comments"`
	CommentsAllowed bool       `json:"commentsAllowed"`
}

type Query struct {
}

type Subscription struct {
}
